name: Update Submodule

on:
  push:
    branches:
      - master
      - develop
    # paths:
    #   - 'submodule-example/**'

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Update Submodule
        run: |
          git submodule update --remote

      # - name: Fetch and Rebase Submodule Changes
      #   run: |
      #     cd submodule-example
      #     git fetch --all
      #     git pull --rebase
      #     cd ..

      - name: Commit Submodule Changes
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "Github Actions Bot"
          git add ./submodule-example
          git commit -am "chore: bump submodule example"
          git push