name: Update submodule

on:
  push:
    branches:
      - master
      - develop
    # paths:
    #   - 'submodule-example/**'

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Update submodule
        run: |
          cd submodule-example
          git fetch --all
          git pull --rebase
          cd ..

      - name: Commit changes
        run: |
          git config --local user.email "mauricioromagnollo@gmail.com"
          git config --local user.name "mauricioromagnollo"
          git add ./submodule-example
          git commit -am "chore: bump submodule example"
          git push